### ISSUE TITLE
aarch64 / arm64 support？

### ISSUE THREAD

**Issue by plumlis** [fcitx/flatpak-fcitx5#1]
I checked flathub with
flatpak remote-ls --arch=aarch64
and found Gnome&KDE sdk already support aarch64

So maybe fcitx5 flatpak can build&run on this  architecture too?

**Comment by wengxt** [comment]
看起来可以用 qemu 但是好像真的很慢很慢…不知道我的服务器能不能跑得动

其实如果你想的话，自己编译可能更快，既然你已经有了 aarch64 的系统

clone 一下这个 repo

执行 flatpak-builder   --install --user --force-clean build  org.fcitx.Fcitx5.yaml （或者其他的 yaml 文件就可以编译并安装了）

**Comment by tinywrkb** [comment]
How about push this to Flathub and take advantage of the CI? you should be able to request that the initial PR will only create a beta branch so it will only be published to flathub-beta repo.

**Comment by wengxt** [comment]
@tinywrkb I was just too lazy to do that, mainly because fcitx have so many package and every package need to be submitted individually...

**Comment by plumlis** [comment]
我编译了 flatpak 版本，目前在非 flatpak 程序下没问题，但是在 flatpak 程序下无法启用。
而且似乎非 flatpak 版本 fcitx 就可以在 flatpak 下用。

**Comment by plumlis** [comment]
好了，换成 fcitx4 的 module 加载 flatpak 就好了
一开始用的 fcitx5 ，不知道是少装了什么还是这个打包有问题，在 x86 64下倒是正常的

**Comment by wengxt** [comment]
如果你说的是环境变量的话，设置成 =fcitx 就好。能同时被 fcitx 和 fcitx5 的 module 接受

**Comment by wengxt** [comment]
正在尝试提交到 flatpak 但流程上肯定比较慢…因为得一个个的审核

**Comment by wengxt** [comment]
已经 push 了三个包上去了，问题不大。

**Comment by wengxt** [comment]
Close this because we'll be updating flatpak package on flathub regularly.
