### ISSUE TITLE
please consider bump the version on flatpak

### ISSUE THREAD

**Issue by CharlesChiuGit** [fcitx/flatpak-fcitx5#10]
as title, current version on flatpak is 5.0.19, but the upstream version is now 5.0.23.
thanks for your time!
![圖片](https://github.com/fcitx/flatpak-fcitx5/assets/32497323/ec49d1bb-f4b2-4c1c-9ef3-4152c72a4d8f)

**Comment by wengxt** [comment]
That was planed. The issue that blocking this upgrade is that, flathub now have more strict requirements on the permission and apparently, fcitx5 does not fully confront their standard for certain reasons. Without adding exception I can't upgrade the one on flathub.

**Comment by wengxt** [comment]
and for certain features we hit some flatpak bug e.g. https://github.com/flatpak/flatpak/issues/5370

**Comment by CharlesChiuGit** [comment]
tks for your explanations! didn't know that before.
