### ISSUE TITLE
Part of mozc_tool does not start up.

### ISSUE THREAD

**Issue by phoepsilonix** [fcitx/flatpak-fcitx5#14]
https://github.com/google/mozc/issues/849

To avoid this problem, here are some suggestions.

fcitx/mozc repository
```
git tag 2.29.5291.102 8d8ea39c6e515c6734041ae6d8b65a2d5b617a1f 
```

fcitx/flatpak-fcitx5 repository
```
diff --git a/org.fcitx.Fcitx5.Addon.Mozc.yaml b/org.fcitx.Fcitx5.Addon.Mozc.yaml
index 03f187f..f7e5826 100644
--- a/org.fcitx.Fcitx5.Addon.Mozc.yaml
+++ b/org.fcitx.Fcitx5.Addon.Mozc.yaml
@@ -36,7 +36,7 @@ modules:
     sources:
       - type: git
         url: https://github.com/fcitx/mozc
-        branch: fcitx
+        tag: 2.29.5291.102
         disable-shallow-clone: true
       - type: patch
         path: zip-code.patch
```

**Comment by phoepsilonix** [comment]
It is a good technique to specify a TAG, especially when updating a stable branch.

**Comment by wengxt** [comment]
No. This repo is for nightly build. Anything that's not working are expected.

For stable build please install from flathub.

**Comment by phoepsilonix** [comment]
Understood. It is enough to remind you next time you submit a PR to FLATHUB.

**Comment by wengxt** [comment]
> Understood. It is enough to remind you next time you submit a PR to FLATHUB.

the flathub pr is created by publish.sh and all the missing fcitx's tag/branch/commit will be filled in by the script.

e.g.
https://github.com/flathub/org.fcitx.Fcitx5.Addon.Mozc/blob/38f7a15d27f846755a6704c4848a4fd1bb48df55/org.fcitx.Fcitx5.Addon.Mozc.yaml#L36
