### ISSUE TITLE
关于 fcitx 5 的 environment variable 

### ISSUE THREAD

**Issue by dogs-1985** [fcitx/flatpak-fcitx5#15]
我不是 technical person，也不是 linux expert，只是一个简单的用户。
我使用的系统是 fedora kinoite 39 版本，wayland，kde plasma 是 5.27.9，用 flatpak 来安装 fcitx5 5.1.5的。

还未升级 kinoite 39 的时候，我的设定是
/home/user/.config/environment.d/envvars.conf
```
GTK_IM_MODULE=fcitx
QT_IM_MODULE=ibus
XMODIFIERS=@im=fcitx
```

Autostart 是：
```
Program: /usr/bin/flatpak 
Argument: run --branch=stable --arch=x86_64 --command=/app/bin/fcitx5 org.fcitx.Fcitx5
```

我可以在 KDE 原生软件和 flatpak 软件上使用中文输入。

系统更新 kinoite 39 后，我发现新的 KDE 可以在 virutal keyboard 上设定 fcitx 5，设定后好像 autostart 那个 flatpak fcitx 5 就不需要了，这样的设定是正确的吗？
还有假如我把 GTK_IM_MODULE 和 QT_IM_MODULE 删掉 ，KDE 上的原生软件如 kwrite、firefox 或者 dolphin 不能使用中文输入，这个也是对的吗？
因为有时候不懂是不是输入得太快如“我们是笨蛋”会出现词如"w吗是笨蛋"，类似。所以才问问是否有什么设定我没改好而出现类似问题。

**Comment by wengxt** [comment]
https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland
https://groups.google.com/g/fcitx/c/sJPrFn0CT2U
https://fcitx-im.org/wiki/Install_Fcitx_5#Install_Fcitx_5_from_Flatpak
