### ISSUE TITLE
fcitx5和flatpak-fcitx5是否能兼容？如何兼容？

### ISSUE THREAD

**Issue by gaboolic** [fcitx/flatpak-fcitx5#16]
我使用linuxmint系统(ubuntu衍生版)，自带fcitx5，不过版本比较低
于是我安装了flatpak-fcitx5，使用flatpak install flathub org.fcitx.Fcitx5
安装成功没有问题，关闭自带的fcitx5打开flatpak-fcitx5能正常输入
但是重启系统之后就不行了，卸载了自带的fcitx5也不行。
加上
```
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx 
```
也不行

但是我改成
```
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus 
```
之后，ibus能用。
关闭ibus 打开flatpak-fcitx5之后，flatpak-fcitx5也能用中文输入了
我不知道使用flatpak-fcitx5的情况下，是否是和fcitx一样的配置？

**Comment by wengxt** [comment]
https://fcitx-im.org/wiki/Install_Fcitx_5#Install_Fcitx_5_from_Flatpak

"Flatpak can not provide the im module you need on your host, so you would still need to install them natively. If your distribution does not have fcitx 5 package, you may use fcitx 4 im module instead (newer than 4.2.9.7), or even ibus im module."

**Comment by gaboolic** [comment]
那我估计export QT_IM_MODULE=ibus 这样 就是用了ibus的im模块了吧……所以能用

最好的方式 是我再安装一下这几个包？

fcitx5-frontend-qt5/fcitx5-qt - 为fcitx5输入法提供Qt5 IM模块。
fcitx5-frontend-gtk2/fcitx5-gkt - 为fcitx5输入法提供GTK2 IM模块。
fcitx5-frontend-gtk3/fcitx5-gtk - 为fcitx5输入法提供GTK3 IM模块。

**Comment by wengxt** [comment]
推荐是那样，不过如果能用你也不一定非要改
