### ISSUE TITLE
Support for KDE Platform 6.7

### ISSUE THREAD

**Issue by dogs-1985** [fcitx/flatpak-fcitx5#44]
```
$ flatpak update
正在查找更新…

信息：运行时 org.kde.Platform 分支 6.6 已结束生命周期，原因：
   We strongly recommend moving to the latest stable version of the Platform and SDK
信息：使用该运行时的应用程序：
   org.fcitx.Fcitx5

无事可做。
```
Hi developer,

I noticed that `fcitx5` currently depends on `org.kde.Platform` 6.6, which has reached end-of-life. Are there plans to support the latest stable version, 6.7? This would help ensure continued support and updates.

Thank you for your work on `fcitx5`!

**Comment by wengxt** [comment]
Updated to 6.8
