### ISSUE TITLE
rime输入法中原用户词库和 lua 脚本无法使用

### ISSUE THREAD

**Issue by grassvalley** [fcitx/flatpak-fcitx5#8]
我以前在深度系统 20.8 下通过其他软件源下载安装的 fcitx5、fcitx5-pinyin、fcitx5-rime、fcitx5-chineseaddons，但是 rime 模块运行不稳定，时常出现崩溃，不得不切换到 pinyin 模块。
前几天下载安装了 flatpak 版的 fcitx5、fcitx5-rime、fcitx5-chineseaddons。发现原来的 rime 词库不可用，使用 rime_dict_manager -i 重新导入也不可用。
另外，已经使用 lua 脚本实现的日期时间输入功能，也不能使用了。
另：flatpak 版的 fcitx5-rime 用户配置文件还是在 .local/share/fcitx5/rime 下吧？

**Comment by wengxt** [comment]
路径问题参考

https://groups.google.com/g/fcitx-announce/c/RsJC-7vkObI （相关的主要是 fcitx5-unstable 内的，flathub 还未更新。）

lua 的问题是编译的时候就没编译进去

**Comment by grassvalley** [comment]
可惜啊！上面的网址是无法访问的…………

**Comment by wengxt** [comment]
~/.var/app/org.fcitx.Fcitx5/data/fcitx5/

**Comment by wengxt** [comment]
已经增加了 lua plugin 的支持
